### ISSUE TITLE
Question: Can we add other tools?

### ISSUE THREAD

**Issue by ayoubAnbara** [spring-office-hours/resources-learning-spring#35]
Hello,
Can I add these tools:
[Bootify](https://bootify.io/)
[JHipster](https://www.jhipster.tech/)
[sdkman](https://sdkman.io/)

**Comment by danvega** [comment]
We created a new resource for frontend related resources that you can find under this org. 

I think create a tools and Ide section with sdkman, intellij, eclipse, code, etc... would be useful.
